[package]
name = "plugin_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
gascat = { path = "../.." }
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
hello_plugin = { path = "../hello_plugin" } 